### ISSUE TITLE
Can't solve any domain

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/net.redeclipse.RedEclipse#3]
It seems this build of Red Eclipse can't connect to any online service. I tried both master server to play online and the IRC support channel inside the game. Both release that couldn't solve the domain.

**Comment by AsciiWolf** [comment]
Hmm, I just tried it and was able to play online without any issue.

**Comment by EchedeyLR** [comment]
Then I don't understand the issue. This is a default installation of Debian 10 with flatpak installed.

**Comment by EchedeyLR** [comment]
How can I provide logs?

**Comment by AsciiWolf** [comment]
Yeah, it should work fine. Try running it from a Terminal: `flatpak run net.redeclipse.RedEclipse`

**Comment by EchedeyLR** [comment]
The only thing I see is just:

> echedey@echedey-500-500ns:~$ flatpak run net.redeclipse.RedEclipse
libpng warning: iCCP: known incorrect sRGB profile

**Comment by EchedeyLR** [comment]
I tried reinstallation on the game and checked other flatpak software installed (I think its impossible but anyways I checked it). I only have other games from flathub and its dependences. Xonotic and OpenArena haven't issues with network connection. In other case I would think I installed something wrong in flatpak but with this, I can't understand.

**Comment by EchedeyLR** [comment]
To solve it I made the following:

* Go to variables option in menu
* Change masterserver domain to its IP
* Try connection to online
* After a bit, I even could connect to the chat lobby that was set on freenode
* I changed masterserver to the domain again
* Rebooted the game, rebooted the computer to confirm is solved
* Confirmed

I don't know why it worked, I wasted time using the game playing offline while it was not working and tested after some matches.

**Comment by AsciiWolf** [comment]
Hmm, this is really weird. It may be a bug in Flatpak or other low-level thing.

**Comment by EchedeyLR** [comment]
At least its solved. I close this issue.

**Comment by EchedeyLR** [comment]
I repopen this issue as the workaround is not working anymore.

**Comment by EchedeyLR** [comment]
Variable list cannot be overwritten on the game. No idea about config file structure and if it is even available.

**Comment by qreeves** [comment]
From the information provided here, it sounds like a domain name resolution issue. This would not be caused by Red Eclipse or the FlatPak and the underlying cause would be elsewhere on the user's system. It is not advised to change from a domain name to an IP address due to the fact that the IP address could change without warning should we change hosting providers or they reallocate IP addresses.

**Comment by EchedeyLR** [comment]
The resolution itself was not an issue in the host system.

Just happened with this packaged app as I even tried to resolve the domain manually using the DNS utilities.

Anyways, since Red Eclipse increased their computing requirements several times, I am not able to test this anymore.
