### ISSUE TITLE
Update to 2.0.0

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/net.redeclipse.RedEclipse#5]
Red Eclipse 2.0.0 was recently [released](https://github.com/redeclipse/base/releases/tag/v2.0.0).

**Comment by AsciiWolf** [comment]
@nedrichards @bilelmoussaoui Upstream developer @Calinou is [interested](https://github.com/redeclipse/base/issues/966#issuecomment-568273004) in helping with the Flatpak, would it be possible to give him a write permissions to this repo? Thanks! :-)

**Comment by bilelmoussaoui** [comment]
@AsciiWolf Invitation sent
