### ISSUE TITLE
Flathub metadata pointing to old repository

### ISSUE THREAD

**Issue by EchedeyLR** [flathub/net.redeclipse.RedEclipse#7]
As given by the title it happens this: https://github.com/redeclipse and https://github.com/red-eclipse

The Flathub links (by now I only checked the "issues" link) are pointing to the repo in https://github.com/red-eclipse that given the explanation in the title, the new organization is at https://github.com/redeclipse and new development is happening there and not in the other organization (last commit on both "base" repos for example).

**Comment by AsciiWolf** [comment]
Oops, you are right! The bugtracker url was not changed to a new one. Thanks for reporting this, I will fix it.
